bodega/apps/categoria/urls.py
from django.conf.urls import url, include
from apps.categoria.views import index_categoria, CategoriaList, CategoriaCreate
from django.contrib.auth.decorators import login_required

urlpatterns = [
	url(r'^$', index_categoria, name=index_categoria),
	url(r'^categoria/listar$', login_required(CategoriaList.as_view()), name='categoria_listar'),
    url(r'^categoria/nueva$', login_required(CategoriaCreate.as_view()), name='categoria_crear'),
	

]

bodega/apps/ingreso/urls.py
from django.conf.urls import url, include
from apps.ingreso.views import index_ingreso, IngresoList, IngresoCreate
from django.contrib.auth.decorators import login_required

urlpatterns = [
	url(r'^$', index_ingreso, name=index_ingreso),
	url(r'^ingreso/listar$', login_required(IngresoList.as_view()), name='ingreso_listar'),
    url(r'^ingreso/nueva$', login_required(IngresoCreate.as_view()), name='ingreso_crear'),
	

]

bodega/apps/producto/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from apps.producto.views import listadousuarios, index, producto_view, producto_list, producto_edit, \
	ProductoList, ProductoCreate, ProductoUpdate

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$', login_required(ProductoCreate.as_view()), name='producto_crear'),
    url(r'^listar', login_required(ProductoList.as_view()), name='producto_listar'),
    url(r'^editar/(?P<pk>\d+)/$', login_required(ProductoUpdate.as_view()), name='producto_editar'),
    url(r'^listado', listadousuarios, name="listado"),
]

bodega/apps/salida/urls.py
from django.conf.urls import url, include
from apps.salida.views import index_salida, SalidaList, SalidaCreate
from django.contrib.auth.decorators import login_required

urlpatterns = [
	url(r'^$', index_salida, name=index_salida),
	url(r'^salida/listar$', login_required(SalidaList.as_view()), name='salida_listar'),
    url(r'^salida/nueva$', login_required(SalidaCreate.as_view()), name='salida_crear'),
	

]

bodega/bodega/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^producto/', include ('apps.producto.urls', namespace="producto")),
    url(r'^categoria/', include ('apps.categoria.urls', namespace="categoria")),
    url(r'^salida/', include ('apps.salida.urls', namespace="salida")),
    url(r'^ingreso/', include ('apps.ingreso.urls', namespace="ingreso")),
    url(r'^stock/', include ('apps.stock.urls', namespace="stock")),
    url(r'^usuario/', include('apps.usuario.urls', namespace='usuario')),
    url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset, 
        {'template_name':'registration/password_reset_form.html',
        'email_template_name': 'registration/password_reset_email.html'}, 
        name='password_reset'), 
    url(r'^password_reset_done', password_reset_done, 
        {'template_name': 'registration/password_reset_done.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
    
]

bodega/templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">

	{% block extrastatic %}
	{% endblock %}

	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<title>{% block title %}Document {% endblock %}</title>
</head>
<body>
<div class="container">

	{% block navbar %}
		<div class="bs-docs-section clearfix">
		    <div class="row">
		        <div class="col-lg-12">
		            <div class="bs-component">
		            	<nav class="navbar navbar-default">
		                	<div class="container-fluid">
		                  		<div class="navbar-header">
		                    		<a class="navbar-brand" href="#">Inicio</a>
		                  		</div>
		                  	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		                    	<ul class="nav navbar-nav">
		                      		<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Producto <span class="caret"></span></a>
				                        <ul class="dropdown-menu" role="menu">
				                        	<li><a href="{% url 'producto:producto_crear' %}">Nuevo Producto</a></li>				        
				                        	<li><a href="{% url 'producto:producto_listar' %}">Listar Productos</a></li>
				                        </ul>
		                      		</li>
		                      		<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Stock <span class="caret"></span></a>
				                        <ul class="dropdown-menu" role="menu">
				                        	<li><a href="{% url 'producto:producto_crear' %}">Listar Stock</a></li>				     
				                        </ul>
		                      		</li>
			                        <li class="dropdown">
			                        	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categoría<span class="caret"></span></a>
			                        	<ul class="dropdown-menu" role="menu">
				                          	<li><a href="{% url 'categoria:categoria_crear' %}">Nueva categoría</a></li>				
				                          	<li><a href="{% url 'categoria:categoria_listar' %}">Listar categorías</a></li>                         
			                        	</ul>
			                        </li>
			                        <li class="dropdown">
			                        	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Ingresos<span class="caret"></span></a>
			                        	<ul class="dropdown-menu" role="menu">
				                          	<li><a href="{% url 'ingreso:ingreso_crear' %}">Ingresar producto</a></li>
				                          	<li><a href="{% url 'ingreso:ingreso_listar' %}">Listar ingresos</a></li>
			                        	</ul>
			                        </li>
			                        <li class="dropdown">
			                        	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Salidas<span class="caret"></span></a>
			                        	<ul class="dropdown-menu" role="menu">
				                          	<li><a href="{% url 'salida:salida_crear' %}">Sacar producto</a></li>				 
				                          	<li><a href="{% url 'salida:salida_listar' %}">Listar salidas</a></li>                         
			                        	</ul>
			                        </li>
		                    	</ul>
		                    	<ul class="nav navbar-nav navbar-right">
		                        	<li class="dropdown"><a href="http://www.uss.cl" onclick="pageTracker._link(this.href); return false;">Universidad San Sebastian</a>
		                        	</li>
		                        	<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Opciones<span class="caret"></span></a>
		                        		<ul class="dropdown-menu" role="menu">
		                          			<li><a href="{% url 'logout' %}">Salir</a></li>
		                        		</ul>
		                      		</li>
		                    	</ul>
		                    </div>
		                </div>
		            </nav>
		        </div>
           	</div>
        </div>
    </div>    

	{% endblock %}


	{% block content %}
	<h4>	Bloque de contenido		</h4>
	{% endblock %}


	{% block footer %}
	{% endblock%}
</div>
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>

	{% block extrajs %}
	{% endblock %}


</body>
</html>