bodega/apps/producto/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from apps.producto.views import listadousuarios, index, producto_view, producto_list, producto_edit, \
	ProductoList, ProductoCreate, ProductoUpdate

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$', login_required(ProductoCreate.as_view()), name='producto_crear'),
    url(r'^listar', login_required(ProductoList.as_view()), name='producto_listar'),
    url(r'^editar/(?P<pk>\d+)/$', login_required(ProductoUpdate.as_view()), name='producto_editar'),
    url(r'^listado', listadousuarios, name="listado"),
]

bodega/bodega/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^producto/', include ('apps.producto.urls', namespace="producto")),
    url(r'^categoria/', include ('apps.categoria.urls', namespace="categoria")),
    url(r'^salida/', include ('apps.salida.urls', namespace="salida")),
    url(r'^ingreso/', include ('apps.ingreso.urls', namespace="ingreso")),
    url(r'^stock/', include ('apps.stock.urls', namespace="stock")),
    url(r'^usuario/', include('apps.usuario.urls', namespace='usuario')),
    url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset, 
        {'template_name':'registration/password_reset_form.html',
        'email_template_name': 'registration/password_reset_email.html'}, 
        name='password_reset'), 
    url(r'^password_reset_done', password_reset_done, 
        {'template_name': 'registration/password_reset_done.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
    
]

bodega/apps/producto/models.py
from django.db import models

# Create your models here.
from apps.categoria.models import Categoria


class Producto(models.Model):
	id_producto = models.IntegerField(primary_key=True)
	nombre = models.CharField(max_length=20)
	descripcion = models.CharField(max_length=40)
	categoria = models.ForeignKey (Categoria, null=True, blank=True, on_delete=models.CASCADE)
	

	def __str__(self):
		return '{}'.format(self.nombre)

bodega/apps/producto/forms.py
from django import forms

from apps.producto.models import Producto

class ProductoForm(forms.ModelForm):
	
	class Meta:
		model = Producto

		fields = [
			'id_producto',
			'nombre',
			'descripcion',
			'categoria',
		]

		labels = {
			'id_producto': 'Id del producto',
			'nombre': 'Nombre del producto',
			'descripcion': 'Descripción del producto',
			'categoria': 'Categoria del producto',
		}


		widgets = {
			'id_producto': forms.TextInput(attrs={'class': 'form-control'}),
			'nombre': forms.TextInput(attrs={'class': 'form-control'}),
			'descripcion': forms.TextInput(attrs={'class': 'form-control'}),
			'categoria': forms.Select(attrs={'class': 'form-control'}),
		}
		






		

bodega/apps/producto/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.core import serializers
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from apps.producto.forms import ProductoForm
from apps.producto.models import Producto

# Create your views here.
def listadousuarios(request):
	lista = serializers.serialize('json', User.objects.all(), fields=['username', 'first_name'])
	return HttpResponse(lista, content_type='application/json')

def index(request):
	return render(request, 'producto/index.html')


def producto_view(request):
	if request.method== 'POST':
		form = ProductoForm (request.POST)
		if form.is_valid():
			form.save()
		return redirect('producto:index')

	else:
		form = ProductoForm()

	return render(request, 'producto/producto_form.html', {'form':form})


def producto_list(request):
	producto = Producto.objects.all().order_by('id_producto')
	contexto = {'producto':producto}
	return render(request, 'producto/producto_list.html', contexto)

def producto_edit(request, id_producto):
	producto = Producto.objects.get(id=id_producto)
	if request.method == 'GET':
		form = ProductoForm(instance=producto)
	else:
		form = ProductoForm(request.POST, instance=producto)
		if form.is_valid():
			form.save()
		return redirect('producto:producto_listar')
	return render(request, 'producto/producto_form.html', {'form':form})


class ProductoList(ListView):
	model = Producto
	template_name = 'producto/producto_list.html'
	paginate_by = 2

class ProductoCreate(CreateView):
	model = Producto
	form_class = ProductoForm
	template_name = 'producto/producto_form.html'
	success_url = reverse_lazy('producto:producto_listar')

class ProductoUpdate(UpdateView):
	model = Producto
	form_class = ProductoForm
	template_name = 'producto/producto_form.html'
	success_url = reverse_lazy('producto:producto_listar')
	

bodega/templates/producto/index.html
{% extends 'base/base.html' %}

{% block title%}
Mascota
{% endblock %}


{% block content %}
<h1>Control de inventario</h1>
{% endblock%}

bodega/templates/producto/producto_form.html
{% extends 'base/base.html %}

{% block content %}
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Guardar</button>
</form>
{% endblock %}

bodega/templates/producto/producto_list.html
{% extends 'base/base.html' %}
{% block content %}
<table class="table table-bordered">
	<thead>
		<tr>
			<td>Id producto</td>
			<td>Nombre</td>
			<td>Descripción</td>
			<td>Categoría</td>
			<td>Acciones</td>
		</tr>	
	</thead>
	<tbody>
		{% if object_list %}
		{% for producto in object_list %}
		<tr>
			<td>{{ producto.id_producto }}</td>
			<td>{{ producto.nombre }}</td>
			<td>{{ producto.descripcion }}</td>

			<td>{{ producto.categoria.nombre }} </td>

			<td>
				<a class="btn btn-primary" href="{% url 'producto:producto_editar' producto.id_producto %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'producto:producto_eliminar' producto.id_producto %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}	
		{% else %}
		<h1>No hay registros de productos</h1>
		{% endif %}
	</tbody>
</table> 
<ul class="pager">
	<li>
		{% if page_obj.has_previous %}
       	 <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
		{% endif %}
        </li>
	<li>
		{% if page_obj.has_next %}
     	 <a href="?page={{ page_obj.next_page_number }}">Next</a> 
    	{% endif %}
    </li>
</ul>
{% endblock%}